name: Deploy to Firebase Hosting

run-name: >-
  ${{ 
    github.event.client_payload.run_name || 
    github.event.head_commit.message || 
    'Manual Trigger'
  }}

on:
  push:
    branches:
      - main
      - release
  repository_dispatch:
    types: [new_blog_post]

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build
        env:
          NEXT_PUBLIC_HASHNODE_HOST: ${{ secrets.NEXT_PUBLIC_HASHNODE_HOST }}

      - name: Deploy to Development
        if: github.event_name == 'push' && github.ref == 'refs/heads/release'
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:development
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to Production
        if: github.event_name == 'repository_dispatch' && github.event.action == 'new_blog_post' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:production
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
